# Generated by Django 4.2.25 on 2025-11-05 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(max_length=6)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=11)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=13)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_reserva', models.CharField(max_length=30, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_reservas.clientes')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id_reserva_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_reservas.reservas')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_reservas.servicios')),
            ],
            options={
                'db_table': 'reserva_servicio',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=13)),
                ('referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_pago', models.CharField(max_length=11)),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_reservas.reservas')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id_reserva_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('estado_asignacion', models.CharField(max_length=8)),
                ('id_habitacion', models.ForeignKey(db_column='id_habitacion', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_reservas.habitaciones')),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_reservas.reservas')),
            ],
            options={
                'db_table': 'reserva_habitacion',
                'unique_together': {('id_reserva', 'id_habitacion')},
            },
        ),
    ]
