# Generated by Django 5.2.7 on 2025-11-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservas', '0002_alter_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='referencia',
            field=models.CharField(blank=True, db_column='referencia', max_length=200, null=True),
        ),
        migrations.RenameField(
            model_name='pagos',
            old_name='referencia',
            new_name='detalles_adicionales',
        ),
    ]
