# Generated by Django 5.2.7 on 2025-12-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_usuarios_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
